# Generated by Django 4.2.2 on 2023-07-06 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_alter_kirrurl_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kirrurl',
            name='test',
        ),
    ]
